apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-control-plane-manager
  namespace: {{ .Release.Namespace }}
---
# Bad, bad Simon
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-control-plane-manager
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unikorn-control-plane-manager
subjects:
- kind: ServiceAccount
  name: unikorn-control-plane-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unikorn-control-plane-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-control-plane-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: unikorn-control-plane-manager
  template:
    metadata:
      labels:
        app: unikorn-control-plane-manager
    spec:
      containers:
      - name: unikorn-control-plane-manager
        image: {{ .Values.controlPlaneManager.image.repository }}:{{ .Values.controlPlaneManager.image.tag }}
        {{- if .Values.monitoring.enabled }}
        ports:
        - name: prometheus
          containerPort: 8080
        {{- end }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-control-plane-manager
      securityContext:
        runAsNonRoot: true
{{- if .Values.monitoring.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: unikorn-control-plane-manager
  namespace: {{ .Release.Namespace }}
  labels:
    service: unikorn-controller
    unikorn-controller: unikorn-control-plane-manager
spec:
  selector:
    app: unikorn-control-plane-manager
  ports:
  - name: prometheus
    port: 8080
    targetPort: prometheus
{{- end }}
