apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-cluster-manager
---
# Bad, bad Simon
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-cluster-manager
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unikorn-cluster-manager
subjects:
- kind: ServiceAccount
  namespace: default
  name: unikorn-cluster-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unikorn-cluster-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-cluster-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-cluster-manager
  template:
    metadata:
      labels:
        app: unikorn-cluster-manager
    spec:
      containers:
      - name: unikorn-cluster-manager
        image: eschercloudai/unikorn-cluster-manager:0.0.0
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-cluster-manager
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: unikorn-cluster-manager
  labels:
    service: unikorn-controller
    unikorn-controller: unikorn-cluster-manager
spec:
  selector:
    app: unikorn-cluster-manager
  ports:
  - name: prometheus
    port: 8080
    targetPort: prometheus
