apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-project-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-project-manager
rules:
- apiGroups:
  - unikorn.eschercloud.ai
  resources:
  - projects
  verbs:
  - list
  - get
  - watch
  - post/status
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unikorn-project-manager
subjects:
- kind: ServiceAccount
  namespace: default
  name: unikorn-project-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unikorn-project-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-project-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-project-manager
  template:
    metadata:
      labels:
        app: unikorn-project-manager
    spec:
      containers:
      - name: unikorn-project-manager
        image: eschercloudai/unikorn-project-manager:0.0.0
        ports:
        - name: prometheus
          containerPort: 8080
      serviceAccountName: unikorn-project-manager
