#!/bin/bash

NAMESPACE=monitoring

while getopts "n:" opt; do
	case ${opt} in
		n) NAMESPACE=${OPTARG};;
	esac
done

kubectl -n ${NAMESPACE} create configmap unikorn --from-file=k8s-dashboard.json=grafana/unikorn.json
kubectl -n ${NAMESPACE} label configmap unikorn grafana_dashboard=1
