apiVersion: unikorn.eschercloud.ai/v1alpha1
kind: ControlPlaneApplicationBundle
metadata:
  name: control-plane-1.2.0
spec:
  version: 1.2.0
  applications:
  - name: vcluster
    reference:
      kind: HelmApplication
      name: vcluster
      version: 0.15.7
  - name: cert-manager
    reference:
      kind: HelmApplication
      name: cert-manager
      version: v1.12.4
  - name: cluster-api
    reference:
      kind: HelmApplication
      name: cluster-api
      version: v0.1.10
