{{- if .Values.dockerConfigs }}
{{- $dot := . }}
{{- range $index, $config := .Values.dockerConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-{{ $index }}
  labels:
    {{- include "unikorn.labels" $dot | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $config }}
{{- end }}
{{- end }}
