apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-monitor
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
{{- with ( include "unikorn.imagePullSecrets" . ) }}
imagePullSecrets:
{{ . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-monitor
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage kubernetes clusters and control planes (my job).
- apiGroups:
  - unikorn.eschercloud.ai
  resources:
  - controlplanes
  - kubernetesclusters
  verbs:
  - list
  - watch
  - update
# Get application bundles
- apiGroups:
  - unikorn.eschercloud.ai
  resources:
  - controlplaneapplicationbundles
  - kubernetesclusterapplicationbundles
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unikorn-monitor
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: unikorn-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unikorn-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-monitor
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-monitor
  template:
    metadata:
      labels:
        app: unikorn-monitor
    spec:
      containers:
      - name: unikorn-monitor
        image: {{ include "unikorn.monitorImage" . }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-monitor
      securityContext:
        runAsNonRoot: true
