openapi: 3.0.3
info:
  title: Unikorn Server
  description: RESTful API service for Unikorn custom resources and UI.
  version: 0.2.0
paths:
  /api/v1/auth/tokens/password:
    description: Password based authentication services.
    post:
      description: |-
        Authenticates against Openstack, and returns a signed and encrypted oauth2
        JWT.  This token has a claim that contains the Openstack authorization token.
        This token can be used to poll allowed Openstack projects and upgrade to a
        project scoped token.
      security:
      - httpBasicAuthentication: []
      responses:
        '200':
          $ref: '#/components/responses/tokenResponse'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '415':
          $ref: '#/components/responses/unsupportedMediaTypeResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/auth/tokens/token:
    description: Token based authentication services.
    post:
      description: |-
        Authenticates against OpenStack, and returns a signed and encrypted oauth2
        JWT.  This token has a claim that contains the Openstack authorization token.
        The Openstack authorization token is project scoped, so the JWT is granted
        the "project" scope, allowing more APIs to be accessed.
      security:
      - oauth2Authentication: []
      requestBody:
        $ref: '#/components/requestBodies/tokenScopeRequest'
      responses:
        '200':
          $ref: '#/components/responses/tokenResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/projects:
    description: Unikorn project services.
    get:
      description: |-
        Lists all Unikorn projects associated with the authenticated user's
        OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    post:
      description: |-
        Creates a new Unikorn project associated with the authenticated user's
        OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/projects/{project}:
    description: Unikorn project services.
    parameters:
    - $ref: '#/components/parameters/project'
    get:
      description: |-
        Gets a Unikorn project associated with the authenticated user's
        OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    delete:
      description: |-
        Deletes a Unikorn project associated with the authenticated user's
        OpenStack project.  This is a cascading operation and will delete all
        contained control planes and clusters.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/projects/{project}/controlplanes:
    description: Unikorn control plane services.
    parameters:
    - $ref: '#/components/parameters/project'
    get:
      description: |-
        Lists all Unikorn control planes contained within the selected Unikorn
        project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    post:
      description: |-
        Creates a new Unikorn control plane within the selected Unikorn project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/projects/{project}/controlplanes/{controlPlane}:
    description: Unikorn control plane services.
    parameters:
    - $ref: '#/components/parameters/project'
    - $ref: '#/components/parameters/controlPlane'
    get:
      description: |-
        Gets a Unikorn control plane from within the selected Unikorn project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    put:
      description: |-
        Updates a Unikorn control plane within the selected Unikorn project.
        This is typically used to modify software versions managed by the
        underlying continuous delivery platform.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    delete:
      description: |-
        Deletes a Unikorn control plane from within the selected Unikorn project.
        This is a cascading operation and will delete all contained clusters.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/projects/{project}/controlplanes/{controlPlane}/clusters:
    description: Unikorn cluster services.
    parameters:
    - $ref: '#/components/parameters/project'
    - $ref: '#/components/parameters/controlPlane'
    get:
      description: |-
        List all Unikorn clusters within the selected Unikorn control plane.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    post:
      description: |-
        Create a new Unikorn cluster within the selected Unikorn control plane.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/projects/{project}/controlplanes/{controlPlane}/clusters/{cluster}:
    description: Unikorn cluster services.
    parameters:
    - $ref: '#/components/parameters/project'
    - $ref: '#/components/parameters/controlPlane'
    - $ref: '#/components/parameters/cluster'
    get:
      description: |-
        Get a Unikorn cluster from within the selected Unikorn control plane.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    put:
      description: |-
        Update a Unikorn cluster within the selected Unikorn control plane.
        This is used to modify cluster paramters e.g. Kubernetes versions or
        scaling (where automatic scaling is not employed), and to modify any
        software componenets deployed within the cluster by the underlying
        continuous deliver platform.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
    delete:
      description: |-
        Delete a Unikorn cluster from within a Unikorn control plane.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/providers/openstack/projects:
    description: OpenStack identity project services.
    get:
      description: |-
        Lists all OpenStack projects that the authenticated user is a member of.
      security:
      - oauth2Authentication: []
      responses:
        '200':
          $ref: '#/components/responses/openstackProjectsResponse'
        '401':
          $ref: '#/components/responses/unauthorizedResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /api/v1/providers/openstack/flavors:
    description: OpenStack compute flavor services.
    get:
      description: |-
        Lists all OpenStack compute flavors that the authenticated user has access
        to within the scope of the OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/providers/openstack/images:
    description: OpenStack compute image services.
    get:
      description: |-
        Lists all OpenStack compute images that the authenticated user has access
        to within the scope of the OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/providers/openstack/availability-zones:
    description: OpenStack compure availability zone services.
    get:
      description: |-
        Lists all OpenStack compute availability zones the authenticated user has
        access to within the scope of the OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/providers/openstack/external-networks:
    description: OpenStack external network services.
    get:
      description: |-
        Lists all OpenStack external networks the authenticated user has access to
        within the scope of the OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
  /api/v1/providers/openstack/key-pairs:
    description: OpenStack key pair services.
    get:
      description: |-
        Lists all OpenStack key pairs the authenticated user has access to within
        the scope of the OpenStack project.
      security:
      - oauth2Authentication:
        - project
      responses:
        '200':
          $ref: '#/components/responses/nullResponse'
components:
  parameters:
    project:
      name: project
      in: path
      description: The Unikorn project name.
      required: true
      schema:
        $ref: '#/components/schemas/stringParameter'
    controlPlane:
      name: controlPlane
      in: path
      description: The Unikorn control plane name.
      required: true
      schema:
        $ref: '#/components/schemas/stringParameter'
    cluster:
      name: cluster
      in: path
      description: The Unikorn cluster name.
      required: true
      schema:
        $ref: '#/components/schemas/stringParameter'
  schemas:
    stringParameter:
      description: A basic string parameter.
      type: string
    oauth2Error:
      description: Generic error message.
      type: object
      required:
      - error
      - error_description
      properties:
        error:
          description: A terse error string expaning on the HTTP error code.
          type: string
          enum:
          # Defined by OAuth2
          - invalid_request
          - unauthorized_client
          - access_denied
          - unsupported_response_type
          - invalid_scope
          - server_error
          - temporarily_unavailable
          # Proprietary
          - not_found
          - method_not_allowed
        error_description:
          description: Verbose message describing the error.
          type: string
    tokenScope:
      description: Password authentication scope.
      type: object
      required:
      - project
      properties:
        project:
          description: Openstack project scoping.
          type: object
          required:
          - id
          properties:
            id:
              description: Openstack project ID.
              type: string
    token:
      desctiption: Authentication token result.
      type: object
      required:
      - token
      properties:
        token:
          description: Authentication token.
          type: string
    openstackProject:
      description: An Openstack project.
      type: object
      required:
      - id
      - name
      properties:
        id:
          description: Globally unique project ID.
          type: string
        name:
          description: The name of the project within the scope of the domain.
          type: string
        description:
          description: A verbose description of the project.
          type: string
    openstackProjects:
      description: A list of Openstack projects.
      type: array
      items:
        $ref: '#/components/schemas/openstackProject'
  requestBodies:
    tokenScopeRequest:
      description: Openstack authentication scoping information.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tokenScope'
  responses:
    nullResponse:
      description: Delete Me
      content:
        application/json: {}
    badRequestResponse:
      description: Request body failed schema validation.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
    unauthorizedResponse:
      description: Authentication failed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
    unsupportedMediaTypeResponse:
      description: Requested media type unspecified or unsupported.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
    internalServerErrorResponse:
      description: An unexpected error occurred, please report.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/oauth2Error'
    tokenResponse:
      description: Authentication was successful.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/token'
    openstackProjectsResponse:
      description: A list of Openstack projects.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/openstackProjects'
  securitySchemes:
    httpBasicAuthentication:
      description: Operation requires HTTP basic authentication.
      type: http
      scheme: basic
    oauth2Authentication:
      description: Operation requires OAuth2 bearer token authentication.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://kubernetes.eschercloud.com/api/v1/tokens/password"
          tokenURL: https://kubernetes.eschercloud.com/api/v1/tokens/token"
          scopes:
            project: Token is scoped to an OpenStack project
