apiVersion: v2
name: unikorn
description: A Helm chart for deploying Unikorn

type: application

version: 0.3.2
appVersion: "0.3.2"

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
