/*
Copyright 2022-2023 EscherCloud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package clusteropenstack

import (
	"context"
	"crypto/sha256"
	"fmt"

	unikornv1 "github.com/eschercloudai/unikorn/pkg/apis/unikorn/v1alpha1"
	"github.com/eschercloudai/unikorn/pkg/constants"
	"github.com/eschercloudai/unikorn/pkg/provisioners"
	provisionererrors "github.com/eschercloudai/unikorn/pkg/provisioners/errors"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"

	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

// releaseName generates a unique helm-compliant release name from the cluster's
// name.
func releaseName(cluster *unikornv1.KubernetesCluster) string {
	// This must be no longer than 53 characters and unique across all control
	// planes to avoid OpenStack network aliasing.
	sum := sha256.Sum256([]byte(cluster.Labels[constants.ControlPlaneLabel] + ":" + cluster.Name))

	hash := fmt.Sprintf("%x", sum)

	return "cluster-" + hash[:8]
}

// CAPIClusterName generates the cluster name that will be generated by helm for
// the given cluster's name.  This is referred to by the cluster autoscaler for
// example.
func CAPIClusterName(cluster *unikornv1.KubernetesCluster) string {
	return releaseName(cluster)
}

// KubeconfigSecretName generates the kubeconfig secret name that will be generated
// by CAPI for the given cluster's name.
func KubeconfigSecretName(cluster *unikornv1.KubernetesCluster) string {
	return releaseName(cluster) + "-kubeconfig"
}

type RemoteClusterGenerator struct {
	// client provides access to the Kubernetes instance where
	// the cluster API resources live.
	client client.Client

	// cluster is the cluster we are referring to.
	cluster *unikornv1.KubernetesCluster
}

// Ensure this implements the remotecluster.Generator interface.
var _ provisioners.RemoteCluster = &RemoteClusterGenerator{}

// NewRemoteClusterGenerator return a new instance of a remote cluster generator.
func NewRemoteClusterGenerator(client client.Client, cluster *unikornv1.KubernetesCluster) *RemoteClusterGenerator {
	return &RemoteClusterGenerator{
		client:  client,
		cluster: cluster,
	}
}

// Name implements the remotecluster.Generator interface.
func (g *RemoteClusterGenerator) Name() string {
	return "kubernetes"
}

// Labels implements the remotecluster.Generator interface.
func (g *RemoteClusterGenerator) Labels() []string {
	labels := []string{g.cluster.Name}

	labels = append(labels, provisioners.ClusterOpenstackLabelsFromCluster(g.cluster)...)

	return labels
}

// Server implements the remotecluster.Generator interface.
func (g *RemoteClusterGenerator) Server(ctx context.Context) (string, error) {
	config, err := g.Config(ctx)
	if err != nil {
		return "", err
	}

	return config.Clusters[config.Contexts[config.CurrentContext].Cluster].Server, nil
}

// Config implements the remotecluster.Generator interface.
func (g *RemoteClusterGenerator) Config(ctx context.Context) (*clientcmdapi.Config, error) {
	log := log.FromContext(ctx)

	secret := &corev1.Secret{}

	secretKey := client.ObjectKey{
		Namespace: g.cluster.Name,
		Name:      KubeconfigSecretName(g.cluster),
	}

	// Retry getting the secret until it exists.
	if err := g.client.Get(ctx, secretKey, secret); err != nil {
		if errors.IsNotFound(err) {
			log.Info("kubernetes cluster kubeconfig does not exist, yielding")

			return nil, provisionererrors.ErrYield
		}

		return nil, err
	}

	config, err := clientcmd.NewClientConfigFromBytes(secret.Data["value"])
	if err != nil {
		return nil, err
	}

	rawConfig, err := config.RawConfig()
	if err != nil {
		return nil, err
	}

	return &rawConfig, nil
}
