name: Unikorn Push
on:
  push:
    branches-ignore:
    - main
    tags-ignore:
    - '*'
env:
  GO_VERSION: 1.19.1
jobs:
  Static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Touch
      run: make touch
    - name: License Checker
      run: make license
    - name: Validate OpenAPI Schema
      run: make touch validate
  Runtime:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Touch
      run: make touch
    - name: Golang CI/Helm Lint
      run: make lint
    - name: Build Images
      run: make charts/unikorn/crds images
    - name: Generated Code Checked In
      run: '[[ -z $(git status --porcelain) ]]'
    - name: Unit Test
      run: make test-unit
