name: Unikorn Push
on:
  push:
    branches-ignore:
    - main
    tags-ignore:
    - '*'
env:
  GO_VERSION: 1.21.1
jobs:
  Static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Touch
      run: make touch
    - name: License Checker
      run: make license
    - name: Validate OpenAPI Schema
      run: make validate
    - name: Validate documentation
      run: sudo apt -y install wbritish && make validate-docs
  Runtime:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Touch
      run: make touch
    - name: Golang CI/Helm Lint
      run: make lint
    - name: Build Images
      run: make charts/unikorn/crds images
    - name: Build Generated Code
      run: make generate
    - name: Generated Code Checked In
      run: '[[ -z $(git status --porcelain) ]]'
    - name: Unit Test
      run: make test-unit
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: cover.html
    - name: Run Codecov
      uses: codecov/codecov-action@v3
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
